name: this is github actions
run-name: this is the run name
on: [push]
jobs:
  test: 
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: sleep 3s && echo test


 

              
